### ISSUE TITLE
state can be mutated without setState

### ISSUE THREAD

**Issue by adriaanwm** [staydecent/pwa-starter#1]
```
export const getState = () => Object.freeze({...state})

> var x = {a: {b: 1}}
> var y = Object.freeze({...x})
> y.a.b = 2
> console.log(x.a.b)
2
```

This can be dangerous if someone uses a method like pop() on an array after calling getState(), then they are mutating state without calling setState

**Comment by staydecent** [comment]
Yup freeze is only shallow. Deep nesting in state and mutable code are both bad practices imo and should be avoided with PRs. The goal of this project is the least amount of code, not the most safe/defensive code.
